### ISSUE TITLE
beforeFeature does not work if the feature or any scenario inside it, is marked with ".only"

### ISSUE THREAD

**Issue by sumeet70** [telefonicaid/tartare#36]
TypeError: Cannot read property 'runnable' of undefined

  at wrappedFn (node_modules\protractor-tartare\index.js:19:20)
    at Context.<anonymous> (node_modules\tartare\lib\interfaces\gherkin.js:346:14)
    at callFn (node_modules\tartare\node_modules\mocha\lib\runnable.js:326:21)
    at Hook.Runnable.run (node_modules\tartare\node_modules\mocha\lib\runnable.js:319:7)
    at next (node_modules\tartare\node_modules\mocha\lib\runner.js:298:10)
    at Immediate._onImmediate (node_modules\tartare\node_modules\mocha\lib\runner.js:320:5)

**Comment by sumeet70** [comment]
Closed by commit d605df2
